### ISSUE TITLE
Replicating with the demo data

### ISSUE THREAD

**Issue by pwwang** [jasminezhoulab/cfSort#3]
Thanks for the great work!

I was trying to replicate the work, using the demo data in the `demo/` directory.
I went pretty smoothly with the `data_prep.py` script. However, when I tried to use `model_train.py` to train the model with the prepared data:
```shell
python model_train.py \
  ../demo/output.train.tfrecords \
  ../demo/output.test.tfrecords \
  ../demo/training_samples.txt \
  1024,512,32 \
  0.05,0.01,0 \
  0.001 \
  32 \
  mae \
  Adam \
  ../t-trained/ \
  20 \
  0
```

I got the following error:

```
2023-07-25 16:47:42.752845: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-25 16:47:42.961096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13775 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:3b:00.0, compute capability: 7.5
2023-07-25 16:47:43.283438: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at example_parsing_ops.cc:94 : INVALID_ARGUMENT: Feature: labels (data type: float) is required but could not be found.
... ...
2023-07-25 16:47:43.283657: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at example_parsing_ops.cc:94 : INVALID_ARGUMENT: Feature: labels (data type: float) is required but could not be found.
Traceback (most recent call last):
2023-07-25 16:47:43.283701: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at example_parsing_ops.cc:94 : INVALID_ARGUMENT: Feature: labels (data type: float) is required but could not be found.
  File "cfSort/codes/model_train.py", line 34, in <module>
```

The `../demo/training_samples.txt` file was generated by (in the `demo` directory):
```shell
awk '$2==1' ../demo/input.label.txt | cut -f1 > training_samples.txt
```

Just in case, I have also tried a subset of `demo/input.label.txt` (with 2nd column == 1, indicating training samples), but I still got the same error.

By the way, here is the version of my tensorflow:

```python
>>> import tensorflow as tf
>>> print(tf.__version__)
2.8.1
```

I had a hard time installing `tensorflow` 2.8.0, as mentioned in your documentation. Could that be the reason for failure? Or I had a wrong understanding of the `samples_list_file`?

Would you mind replicating the environment with conda and sharing the `environment.yml` file? So that it's easier for people to replicate the environment.

Thanks in advance for your time and concern.

**Comment by DashuoLI** [comment]
Hi,

I appreciate your interest in our work!

I ran exactly the same command and also got the same error. The reason is that during model training, we need to use `../demo/output.test.tfrecords` instead of `../demo/output.test.tfrecords`.  The `data_prep.py` script will generate three files, `*.train.tfrecords`, `*.valid.tfrecords`, and `*.test.tfrecords`. The first two files are used as the training data and the validation data during the training process. The validation data is for model evaluation during training and early stopping. These two files contain both the features and the label for every sample. The test file is used in `model_pred.py`. It only contains the features. Therefore, this file contains a different data structure from the other two files, which may be the core reason that leads to this error. 

The `samples_list_file` is actually deprecated and plays no role in the `model_train.py`. The training samples are identified and saved in the `data_prep.py` step. Therefore, the issue should not come from `samples_list_file`. We apologize for the confusion.

If you want to train a toy model using the demo data, please change the `TOTAL_TRAINING_SAMPLES` in the `model_train.py`. The current value of this parameter is for the complete model training. Using the demo data, the parameter should be set to 151. 

Please note that training on the demo data can not reproduce the DNN models in the manuscript. The demo data only contains 151 training samples due to the limit of file size on GitHub. The models in the manuscript were trained on >250K samples. The pre-trained models were deposited on https://zenodo.org/record/7884243.

We uploaded `environment.yml` in the `codes` folder.

**Comment by pwwang** [comment]
Worked perfectly!

I supposed you meant:

> we need to use `../demo/output.valid.tfrecords` instead of `../demo/output.test.tfrecords`.

rather than:

> we need to use `../demo/output.test.tfrecords` instead of `../demo/output.test.tfrecords`.

We might also have to update the README file for `model_train.py` to change the `test_file` to `valid_file` for the 2nd argument.

Thanks again for you time!
