### ISSUE TITLE
Row annotation of output from pre-trained models

### ISSUE THREAD

**Issue by DaGaMs** [jasminezhoulab/cfSort#7]
Hi,

I now managed to run cfSort on some of our data 🎉 I get a matrix of `n_sample` rows by 29 columns, which seems correct. However, I've not been able to find out which _tissue_ each column refers to! Could you let me know the list of tissue names to put as column names?

Thanks in advance, best wishes,
Ben

**Comment by DashuoLI** [comment]
Thank you for your interest. This issue was addressed in #4 

The tissue names are in alphabetical order, adipose_tissue, adrenal_gland, bladder, blood_vessel, brain, breast, cervix_uteri, colon, esophagus, fallopian_tube, heart, kidney, liver, lung, muscle, nerve, ovary, pancreas, pituitary, prostate, salivary_gland, skin, small_intestine, spleen, stomach, testis, thyroid, uterus, vagina, and WBC.

**Comment by DaGaMs** [comment]
Thanks, I missed that bit!

**Comment by DaGaMs** [comment]
Actually - that's 30 tissue names you listed, but the output for both dnn1 and dnn2 has only 29 columns 🤔 Any idea what happened there?

**Comment by DashuoLI** [comment]
Sorry for the mistake. There is no "brain" tissue type there. 

The correct names are adipose_tissue, adrenal_gland, bladder, blood_vessel, breast, cervix_uteri, colon, esophagus, fallopian_tube, heart, kidney, liver, lung, muscle, nerve, ovary, pancreas, pituitary, prostate, salivary_gland, skin, small_intestine, spleen, stomach, testis, thyroid, uterus, vagina, and WBC.
